In [17]:

import torch 

Example sentence: `I love you`

In [18]:
input = torch.tensor([0,1,2])
input,input.shape

(tensor([0, 1, 2]), torch.Size([3]))

In [19]:
from torch.nn import Embedding

embedding = Embedding(3,4)
embedded_sentence =embedding(input)
embedded_sentence,embedded_sentence.shape


(tensor([[ 0.9082, -0.4524, -0.3170, -0.4982],
         [ 1.1384,  0.2863,  1.5047,  0.7825],
         [ 0.4415, -1.3736, -0.4298,  0.0815]], grad_fn=<EmbeddingBackward0>),
 torch.Size([3, 4]))

In [20]:

q_vector=[]
k_vector=[]
v_vector=[]
q_vector.clear()
k_vector.clear()
v_vector.clear()

Wq = torch.rand(4,3)
Wk = torch.rand(4,3)
Wv = torch.rand(4,3)


for word in embedded_sentence:
    q_vector.append(torch.matmul(word.unsqueeze(0),Wq))
    k_vector.append(torch.matmul(word.unsqueeze(0),Wk))
    v_vector.append(torch.matmul(word.unsqueeze(0),Wv))


In [21]:
q_vector

[tensor([[ 0.1800, -0.1395,  0.1841]], grad_fn=<MmBackward0>),
 tensor([[2.0398, 2.3036, 2.9367]], grad_fn=<MmBackward0>),
 tensor([[-0.4120, -0.1387, -0.0024]], grad_fn=<MmBackward0>)]

In [22]:
k_vector , k_vector[0].shape

([tensor([[-0.6261, -0.4828, -0.4296]], grad_fn=<MmBackward0>),
  tensor([[2.3565, 1.1809, 2.9514]], grad_fn=<MmBackward0>),
  tensor([[-1.1541, -0.9341, -1.1287]], grad_fn=<MmBackward0>)],
 torch.Size([1, 3]))

In [23]:
v_vector

[tensor([[-3.3073e-01, -2.2443e-04, -5.9802e-01]], grad_fn=<MmBackward0>),
 tensor([[1.1377, 1.4576, 2.3103]], grad_fn=<MmBackward0>),
 tensor([[-0.9519, -0.5821, -0.7040]], grad_fn=<MmBackward0>)]

In [29]:
k_vector

[tensor([[-0.6261, -0.4828, -0.4296]], grad_fn=<MmBackward0>),
 tensor([[2.3565, 1.1809, 2.9514]], grad_fn=<MmBackward0>),
 tensor([[-1.1541, -0.9341, -1.1287]], grad_fn=<MmBackward0>)]

In [35]:
q_vector[0].shape

torch.Size([1, 3])

In [38]:
torch.dot(q_vector[0].squeeze(0),k_vector[0].squeeze(0)).item()

-0.1244596391916275

In [33]:
def calculate_attention(q_vector,k_vector):
    for q in q_vector:
        for k in k_vector:
            print(k)

calculate_attention(q_vector,k_vector)


tensor([[-0.6261, -0.4828, -0.4296]], grad_fn=<MmBackward0>)
tensor([[2.3565, 1.1809, 2.9514]], grad_fn=<MmBackward0>)
tensor([[-1.1541, -0.9341, -1.1287]], grad_fn=<MmBackward0>)
tensor([[-0.6261, -0.4828, -0.4296]], grad_fn=<MmBackward0>)
tensor([[2.3565, 1.1809, 2.9514]], grad_fn=<MmBackward0>)
tensor([[-1.1541, -0.9341, -1.1287]], grad_fn=<MmBackward0>)
tensor([[-0.6261, -0.4828, -0.4296]], grad_fn=<MmBackward0>)
tensor([[2.3565, 1.1809, 2.9514]], grad_fn=<MmBackward0>)
tensor([[-1.1541, -0.9341, -1.1287]], grad_fn=<MmBackward0>)
