In [40]:

import torch 

Example sentence: `I love you`

In [41]:
input = torch.tensor([0,1,2])
input,input.shape

(tensor([0, 1, 2]), torch.Size([3]))

In [42]:
from torch.nn import Embedding

embedding = Embedding(3,4)
embedded_sentence =embedding(input)
embedded_sentence,embedded_sentence.shape


(tensor([[-0.5389, -0.1476,  0.0763,  1.2217],
         [-0.8461, -0.1356,  1.5055,  0.2531],
         [-0.6635,  0.4190, -1.3850, -0.0317]], grad_fn=<EmbeddingBackward0>),
 torch.Size([3, 4]))

In [43]:

q_vector=[]
k_vector=[]
v_vector=[]
q_vector.clear()
k_vector.clear()
v_vector.clear()

Wq = torch.rand(4,3)
Wk = torch.rand(4,3)
Wv = torch.rand(4,3)


for word in embedded_sentence:
    q_vector.append(torch.matmul(word.unsqueeze(0),Wq))
    k_vector.append(torch.matmul(word.unsqueeze(0),Wk))
    v_vector.append(torch.matmul(word.unsqueeze(0),Wv))


In [44]:
q_vector

[tensor([[0.2723, 0.2406, 0.7984]], grad_fn=<MmBackward0>),
 tensor([[0.2367, 0.7711, 0.9227]], grad_fn=<MmBackward0>),
 tensor([[-0.7887, -0.5633, -1.4106]], grad_fn=<MmBackward0>)]

In [45]:
k_vector , k_vector[0].shape

([tensor([[1.1163, 0.6530, 0.1827]], grad_fn=<MmBackward0>),
  tensor([[1.0899, 0.0861, 0.9851]], grad_fn=<MmBackward0>),
  tensor([[-0.9386,  0.1854, -0.7626]], grad_fn=<MmBackward0>)],
 torch.Size([1, 3]))

In [46]:
v_vector

[tensor([[0.7486, 0.7158, 0.7152]], grad_fn=<MmBackward0>),
 tensor([[0.2388, 1.0195, 0.2980]], grad_fn=<MmBackward0>),
 tensor([[-0.5178, -1.7597, -1.0042]], grad_fn=<MmBackward0>)]

In [47]:
k_vector

[tensor([[1.1163, 0.6530, 0.1827]], grad_fn=<MmBackward0>),
 tensor([[1.0899, 0.0861, 0.9851]], grad_fn=<MmBackward0>),
 tensor([[-0.9386,  0.1854, -0.7626]], grad_fn=<MmBackward0>)]

In [48]:
q_vector[0].shape

torch.Size([1, 3])

`Attention --> (I) x(I)  in I love you`

In [49]:
torch.dot(q_vector[0].squeeze(),k_vector[0].squeeze()).item()

0.6069552302360535

In [50]:
q_vector[0]

tensor([[0.2723, 0.2406, 0.7984]], grad_fn=<MmBackward0>)

In [61]:
attention_scores=[]
attention_scores.clear()
def calculate_attention(q_vector,k_vector):
    for q in q_vector:
        word_score=[]
        for k in k_vector:
            score = torch.dot(q.squeeze(),k.squeeze()).item()
            word_score.append(score)

        attention_scores.append(word_score.copy())
       
        word_score.clear()
calculate_attention(q_vector,k_vector)


In [62]:
attention_scores

[[0.6069552302360535, 1.10406494140625, -0.8198787569999695],
 [0.9363361597061157, 1.2333495616912842, -0.782888650894165],
 [-1.505926489830017, -2.297654390335083, 1.7115082740783691]]